language: python
dist: xenial

python:
  - "3.5"
  - "3.8"

services:
  - xvfb

before_install:
  - wget https://github.com/mozilla/geckodriver/releases/download/v0.15.0/geckodriver-v0.15.0-linux64.tar.gz
  - mkdir geckodriver
  - tar -xzf geckodriver-v0.15.0-linux64.tar.gz -C geckodriver
  - export PATH=$PATH:$(pwd)/geckodriver
  - pip install -U pip
  - export BOTO_CONFIG=/dev/null
install:
  - make requirements
script:
  - make selfcheck
  - make quality
  - make test
  - travis_retry make validate_translations

notifications:
  email: false
addons:
  firefox: "52.0.1"
