version: 2.1

orbs:
  browser-tools: circleci/browser-tools@1.2.3

commands:
  install-dependencies:
    steps:
      - run:
          name: Install OS dependencies
          command: |
            sudo apt update && sudo apt install -y nodejs npm gettext
            # Upgrade nodejs after node-gyp installed properly
            curl -sL https://deb.nodesource.com/setup_16.x | sudo -E bash -
            sudo apt install -y nodejs
      - run:
          name: Install project dependencies
          command: |
            pip install tox
            make requirements

jobs:
  validate-translations:
    docker:
      - image: cimg/python:3.8
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Validate translations
          command: |
            make validate_translations
  quality:
    docker:
      # Always run with the minimum supported version
      # to avoid new language feature checkes like f-strings
      - image: cimg/python:2.7
    steps:
      - checkout
      - install-dependencies
      - run:
          name: Check code quality
          command: |
            tox -e quality
  test:
    parameters:
      image:
        type: string
      tox-env:
        type: string
    docker:
      - image: << parameters.image >>
    steps:
      - checkout
      - browser-tools/install-firefox
      - browser-tools/install-geckodriver
      - install-dependencies
      - run:
          name: Test << parameters.tox-env >>
          command: |
            tox -e << parameters.tox-env >>

workflows:
  version: 2
  main:
    jobs:
      - quality
      - validate-translations
      - test:
          requires:
            - quality
            - validate-translations
          matrix:
            parameters:
              image: ["cimg/python:2.7-browsers"]
              tox-env: ["py27-django111"]
      - test:
          requires:
            - quality
            - validate-translations
          matrix:
            parameters:
              image: ["cimg/python:3.6-browsers"]
              tox-env: ["py36-django22", "py36-django32"]
      - test:
          requires:
            - quality
            - validate-translations
          matrix:
            parameters:
              image: ["cimg/python:3.8-browsers"]
              tox-env: ["py38-django22", "py38-django32"]
